Updated Dakota's documentation to include version recommendation
watts-dev/watts pull request #111
Opened 2023-08-25 21:54 UTC by zhieejhia93

# Description

Updated Dakota's documentation to recommend users to use Dakota v6.9 with WATTS.

Fixes # (issue)

# Checklist:

- [ ] My code follows the [style guidelines](https://watts.readthedocs.io/en/latest/dev/styleguide.html)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have updated the CHANGELOG.md file (if applicable)
- [ ] I have successfully run examples that may be affected by my changes

2023-08-25 21:54 UTC, zhieejhia93 commented
@nstauff  Please have a look. Thanks!

2023-08-26 00:30 UTC, nstauff requested changes

2023-08-26 00:30 UTC, nstauff commented on doc/source/user/plugins.rst
> +lead to complications or issues with WATTS.
Note: Users are advised to use Dakota v6.18 or latest, as earlier versions may potentially
lead to complications or issues with WATTS.

2023-08-26 00:35 UTC, zhieejhia93 commented
@nstauff I updated the sentence as requested.

2023-08-26 00:40 UTC, nstauff approved these changes

2023-08-26 00:40 UTC, merged