[WIP] GCMat plugin
watts-dev/watts pull request #114
Opened 2024-08-15 03:14 UTC by JiaZhou-PU

# Description

Please include a summary of the change and which issue is fixed if applicable. Please also include relevant motivation and context.

Fixes # (issue)

# Checklist:

- [ ] My code follows the [style guidelines](https://watts.readthedocs.io/en/latest/dev/styleguide.html)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have updated the CHANGELOG.md file (if applicable)
- [ ] I have successfully run examples that may be affected by my changes

2024-08-15 04:01 UTC, JiaZhou-PU commented
@paulromano Ready for Review

2024-08-15 04:04 UTC, JiaZhou-PU commented
@paulromano @nstauff  Ready for review

2024-08-16 12:56 UTC, nstauff requested changes
Thanks @JiaZhou-PU  - this looks quite good but I have a few comments to request improvements in documentation

2024-08-16 12:56 UTC, nstauff commented on doc/source/user/plugins.rst
> +region    final demand agent	final demand product	reference product	unit	2010	2011	2012	2013	2014	2015	2016	2017	2018	2019	2020	2021	2022	2023	2024	2025	2026	2027	2028	2029	2030
Use a code-block to improve formatting?

` .. code-block:: jinja `

2024-08-16 12:56 UTC, nstauff commented on doc/source/user/plugins.rst
> +The :class:`~watts.PluginGCMat` class enables simulations with Argonne’s global critical materials agent-based model (GCMat) to simulate dynamic economic markets that are composed of agents who have
break down this sentence. `(GCMat). This code simulates...`

2024-08-16 12:56 UTC, nstauff commented on examples/1App_GCMat/README.md
> +This example provides a demonstration for using WATTS explore supply chain dynamics and uncertainty under nuclear scenarios of Uranium fuel demand growth or shrinkage, supply disruptions.
`This example provides a demonstration for using WATTS to explore supply chain dynamics and uncertainty with GCMat under nuclear scenarios of Uranium fuel demand growth or shrinkage, supply disruptions.`

2024-08-16 12:56 UTC, nstauff commented on examples/1App_GCMat/watts_exec.py
> +final_demand_org = {'2025': 129942.80467537, '2026': 131242.232722123, '2027': 132554.655049345, '2028': 133880.201599838, '2029': 135219.003615836, '2030': 136571.193651995, '2031': 137936.905588515
add comments to explain what those numbers are - are we selecting 1 set of projections throughout 2035?

2024-08-16 12:56 UTC, nstauff commented on examples/1App_GCMat/watts_exec.py
> +for i in range(2025, 2036):
explain we are running the GCmat at every year

2024-08-16 12:56 UTC, nstauff commented on examples/1App_GCMat/watts_exec.py
> +scenario.
it is not clear to me what type of simulations we are running. Are we running a set of GCMat scenarios with different sensitivity on input parameters? Or just one reference scenario? Please clarify in comments.

2024-08-16 12:56 UTC, nstauff commented on examples/1App_GCMat/watts_exec.py
> +for end_year, output_folder in zip(end_years, output_folders):
explain why we need a loop for GCMat calculations

2024-08-26 16:20 UTC, JiaZhou-PU commented
@nstauff Thanks! Comments are addressed, and ready to merge. @paulromano Thank you for the fixes.

2024-08-27 12:31 UTC, nstauff approved these changes
Thanks @JiaZhou-PU

2024-08-27 13:10 UTC, merged