Allow extra templated input files
watts-dev/watts pull request #32
Opened 2022-04-04 21:44 UTC by amandalund

This PR modifies the `Plugin` class to accept extra templated input files (see #13):

`watts.PluginX('main_tmpl', extra_inputs=['extra_inp'], extra_template_inputs=['extra_tmpl1, 'extra_tmpl2'])`

It also adds a unit test and reduces some of the code duplication in the plugin `postrun` methods.

2022-04-05 00:23 UTC, nstauff commented on src/watts/plugin.py
> +        """Get the data needed to create the postrun results object
This is great - thanks @amandalund

2022-04-05 00:25 UTC, nstauff commented
This looks great - @zhieejhia93 : could you please review and add a test case based on SAS? Thanks.

2022-04-05 00:29 UTC, nstauff requested changes

2022-04-05 00:29 UTC, nstauff commented on src/watts/plugin.py
> +        for render_template in self.extra_render_templates:
We need to add an example with `extra_template_inputs` in the `example/` (based on SAS), and mention this option in the Documentation.

2022-04-08 20:17 UTC, zhieejhia93 commented
Thanks for working on this @amandalund . I tested the PR with a SAS example that has multiple input files and it worked. 

@nstauff once this PR is merged, I will submit a new PR with the new SAS example. The SAS plugin also requires a couple of minor changes to work with Amanda's implementation. I will update that in the next PR. Thanks.

2022-04-08 20:17 UTC, zhieejhia93 approved these changes

2022-04-18 17:11 UTC, paulromano approved these changes
Thanks @amandalund!

2022-04-18 17:55 UTC, nstauff commented on src/watts/plugin.py
> +        for render_template in self.extra_render_templates:
This will be done in another MR by @zhieejhia93

2022-04-18 17:55 UTC, nstauff approved these changes

2022-04-18 17:55 UTC, merged

2022-04-18 17:58 UTC, amandalund commented
Thanks for the reviews!