RELAP5-3D plugin
watts-dev/watts pull request #37
Opened 2022-04-21 16:33 UTC by zhieejhia93

A plugin to execute RELAP5-3D with WATTS. Several things to highlight:

- The default `run_proc()` does not work with RELAP5. Seems like it's because of the extra argument of 'stdout' to subprocess.Popen(). As a work around, I explicitly use subprocess.Popen() in the plugin to run the executable.
- This version of RELAP5-3D does not generate a CSV file. Instead, it generates a text file with a specific formatting. The text file needs to be converted to csv before the results can be extracted by the plugin. Other (newer) versions of RELAP5-3D is able to generate output csv files directly. The text-to-csv conversion in the plugin may need to be updated or removed in the future. 
- I also updated the documentation, added an example, and updated the test case for the new plugin.

2022-04-23 01:12 UTC, nstauff requested changes
thanks for the plugin - I just had minor editorial revisions.

2022-04-23 01:12 UTC, nstauff commented on doc/source/user/usage.rst
> +~~~~~~~~~~~~~~~~~~~~
wrong title.

2022-04-23 01:12 UTC, nstauff commented on examples/1App_RELAP5_SingleChannel/README.md
> +- [__relap5_template__](relap5_template): Templated SAS input.
update to `Templated RELAP5 input.`

2022-04-23 01:13 UTC, nstauff commented
@lingzou I am adding you as reviewer - could you please test this plugin out? I don't have access to RELAP5 so would not be able to check it works. Thanks!

2022-04-25 13:58 UTC, lingzou commented
> @lingzou I am adding you as reviewer - could you please test this plugin out? I don't have access to RELAP5 so would not be able to check it works. Thanks!

@nstauff If not urgent, I will test it a bit later after setting up RELAP5 on my computer.

2022-04-26 00:59 UTC, nstauff commented
> > @lingzou I am adding you as reviewer - could you please test this plugin out? I don't have access to RELAP5 so would not be able to check it works. Thanks!
> 
> @nstauff If not urgent, I will test it a bit later after setting up RELAP5 on my computer.

Yes, this is not urgent. thanks!

2022-05-04 15:22 UTC, lingzou commented
@nstauff As discussed, I only performed a "visual" check on the MR, and it looks good to me.

2022-05-04 15:22 UTC, lingzou commented
@nstauff As discussed, I only performed a "visual" check on the MR, and it looks good to me.

2022-05-04 18:25 UTC, nstauff commented
Thanks @lingzou - I will approve the PR once @zhieejhia93 addresses my minor editorial revisions requested!

2022-05-04 21:11 UTC, nstauff approved these changes

2022-05-04 21:12 UTC, nstauff commented
Thanks @zhieejhia93 - note that the CI tests are failing. Could you check what is going on?

2022-05-04 21:15 UTC, zhieejhia93 commented
@nstauff Ya, I am looking into that right now. Seems to be due to the changes that Paul made recently. I should be able to fix that.

2022-05-04 21:36 UTC, zhieejhia93 commented
@nstauff The changes passed the CI tests. Everything should be good now. Thanks
=

2022-05-05 00:45 UTC, merged